services:
  react-search-ui:
    image: node:18
    container_name: react-search-ui
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
    networks:
      - search-network

networks:
  search-network:
    driver: bridge
